### ISSUE TITLE
browser compatible version on npm

### ISSUE THREAD

**Issue by istrau2** [stellar/bower-js-stellar-sdk#1]
I generally use npm to manage my browser dependencies (as opposed to bower). Is there any way to get this repository up on npm as well (I am having problem trying to use `npm install stellar-sdk` in the browser). Thanks.

**Comment by bartekn** [comment]
What problems do you have with installing stellar-sdk from npm? It should
work.

17.03.2017 1:59 AM "istrau2" <notifications@github.com> napisał(a):

**Comment by istrau2** [comment]
@bartekn Hmmm not sure, getting a bunch of node-gyp errors which I guess has nothing to do with my original issues. Not sure.

**Comment by istrau2** [comment]
I guess what I would like is to just download the one javascript file in this repo without having to worry about node-gyp and ed25519@0.0.4 (which isn't successfully installing either).

**Comment by bartekn** [comment]
@istrau2, ed25519 is an optional dependency. You should be able to use stellar-sdk without it.
