### ISSUE TITLE
 test of creativePassiveOffer error on browser

### ISSUE THREAD

**Issue by seektoknow** [stellar/bower-js-stellar-sdk#2]
While doing some test of creativePassiveOffer on browser,  it end up with error messages , as  the error1 and error2 of attachments. (Also attach my HTML test docs)
It works well in Node.js environment by executing the same codes, and I’ve checked the parameter of Passive offer are correct, is there anything I missed?

error message and docs in this url
https://drive.google.com/open?id=1ZHd66ibwOgfWaswTCXrW24td7VXnRCnp 

Thank you your support

**Comment by bartekn** [comment]
Tracking in https://github.com/stellar/js-stellar-sdk/issues/106
