### ISSUE TITLE
Please don't push pre-releases into master branch

### ISSUE THREAD

**Issue by MisterTicot** [stellar/bower-js-stellar-sdk#4]
The history is kind of confusing now: 1.0.2 -> 2.0.x beta -> 1.0.3 -> More 2.0.x beta.

Wouldn't it better to push pre-releases in a dedicated branch? I mean, I would expect this repo master branch to always contains a stable release - at some point master HEAD was actually an alpha release.

**Comment by ire-and-curses** [comment]
Duplicate of [js-stellar-sdk:348](https://github.com/stellar/js-stellar-sdk/issues/348)
