### ISSUE TITLE
`stellar-sdk` is not getting packaged nor published for Bower

### ISSUE THREAD

**Issue by cujo30227** [stellar/bower-js-stellar-sdk#7]
Great work on packaging the Stellar SDK into a single js-file for front-end development!!

I had two questions:
- Do you intend to regularly update the package? I noticed that the Typescript version is on 9.0.0 now?
- Would you be able to offer something similar on Helium --> https://github.com/helium/helium-js   

Thanks!

**Comment by Shaptic** [comment]
Hi @cujo30227! Thanks for bringing this to my attention: as you can see in the [commit history](https://github.com/stellar/bower-js-stellar-sdk/commits/master), this repo was typically updated by Travis CI. When we moved to GitHub actions (e.g. stellar/js-stellar-base#457), this CD task must have gotten lost in the fray. I'll try to get that out soon, so that we can get the v9.0.0 version published.

For your second question re: Helium, can you elaborate? I'm not sure what you mean by "something similar." The linked repo looks very similar to our [Typescript repo](https://github.com/stellar/js-stellar-sdk/).

**Comment by cujo30227** [comment]
Excellent, really appreciated!

One the 2nd topic: for the Stellar SDK, your repo provides a single js file (stellar-sdk.js) that is ideal for front end integration, just adding the js file in the script. I assume that the Typescript repo for Helium could also be packaged in that way (e.g. helium-sdk.js), but I haven't figured out how. I thought that you might have gone through the same process for Stellar?

Thanks!

**Comment by Shaptic** [comment]
Ah, I see! I looked into their packaging structure, and while it does look like there's a `yarn build` command that should produce some raw JS, I couldn't get it to work. I see you opened helium/helium-js#252; it might be your best bet to wait for a reply.

I believe we use gulp alongside babel (to transpile) and webpack (to bundle) (see our [gulpfile.js](https://github.com/stellar/js-stellar-sdk/blob/master/gulpfile.js)) to turn everything into a single JS file, so you could also try doing the same. I wasn't around when the build pipeline itself was authored, though, so unfortunately I can't walk you through the process without a lot of digging.

**Comment by cujo30227** [comment]
Ok cool, thanks for looking into that and for the tip! I'm going to play with gulp/babel/webpack a bit :)
I'll also monitor https://github.com/helium/helium-js/issues/252 
Thanks!

**Comment by cujo30227** [comment]
Hi there, sorry to bother again. Are the changes in  https://github.com/stellar/js-stellar-sdk  automatically propagating here? I see js-stellar-sdk is on version 9.1.0 already...
Thanks!

**Comment by Shaptic** [comment]
Huh, that's odd... I made it publish here the same way it publishes to npm in stellar/js-stellar-sdk#725, but I guess it didn't work. I'll look into this again when I get bandwidth!

**Comment by cujo30227** [comment]
Thanks !

**Comment by Shaptic** [comment]
This shouldn't have been auto-closed :facepalm:

**Comment by Shaptic** [comment]
I think it works now, @cujo30227! :tada: (see 7e6b246f0388bf1167de3e81aaa2c3acfd620063)

**Comment by cujo30227** [comment]
Cool, thank you so much!
